#!/bin/bash
while [ 2 -gt 1 ]
do
	TEMP=`cat /sys/class/thermal/thermal_zone0/temp`
	echo $TEMP
	sleep 5
	if [[ $TEMP -gt 70000 ]]  
	then
		echo "the temp is more than 70"
		echo 100 > /sys/kernel/xpi_gamecon/fan
	else
		echo 100 > /sys/kernel/xpi_gamecon/fan 
	fi
done
